name: Node.js CI

on:
  push:
    branches:
      - main

      
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# build docker image , # push docker image to ecr 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::242201291893:role/github_ecr_role
        aws-region: us-west-2


    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2



    - name: Build, tag, and push docker image to Amazon ECR
      id: build-image
      env:
        REGISTRY: ${{ steps.242201291893.dkr.ecr.us-west-2.amazonaws.com/ecr_practice }}
        REPOSITORY: ga_ecr
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        
# ready to push
  


 
 